# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_data": "00_data.ipynb"}

modules = ["data.py"]

doc_url = "https://andrewm4894.github.io/netdata_pandas/"

git_url = "https://github.com/andrewm4894/netdata_pandas/tree/master/"

def custom_doc_links(name): return None
