# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_chart": "00_data.ipynb",
         "get_charts": "00_data.ipynb",
         "get_data": "00_data.ipynb",
         "do_stuff": "01_utils.ipynb"}

modules = ["data.py",
           "utils.py"]

doc_url = "https://netdata.github.io/netdata-pandas/"

git_url = "https://github.com/netdata/netdata-pandas/tree/master/"

def custom_doc_links(name): return None
